Samples/Sample.AspNetCore/Controllers/CheckoutController.cs
using Iamport.RestApi;
using Microsoft.AspNetCore.Mvc;
using Sample.AspNetCore.Repositories;
using Sample.AspNetCore.ViewModels;
using System;

namespace Sample.AspNetCore.Controllers
{
    /// <summary>
    /// 구매 정보 관련 컨트롤러
    /// </summary>
    [Route("[Controller]")]
    public class CheckoutController : Controller
    {
        private readonly CheckoutRepository checkoutRepository;
        private readonly IamportHttpClientOptions clientOptions;
        public CheckoutController(
            CheckoutRepository checkoutRepository,
            IamportHttpClientOptions clientOptions)
        {
            this.checkoutRepository = checkoutRepository ?? throw new ArgumentNullException(nameof(checkoutRepository));
            this.clientOptions = clientOptions ?? throw new ArgumentNullException(nameof(clientOptions));
        }

        /// <summary>
        /// 결제 요청(Checkout; 혹은 구매) 페이지
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View(new RegisterCheckoutModel());
        }

        /// <summary>
        /// 구매 정보를 등록하고 결제 페이지로 이동합니다.
        /// </summary>
        /// <param name="model">구매 정보</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RegisterCheckoutModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            // 새 구매 정보 저장
            var checkout = model.ToCheckout();
            checkoutRepository.Add(checkout);

            // 결제 페이지로 이동
            return RedirectToAction(nameof(Gateway), new { id = checkout.Id });
        }

        /// <summary>
        /// 해당 구매 정보를 결제하는 결제 게이트웨이 페이지.
        /// </summary>
        /// <param name="id">구매 정보 Id</param>
        /// <returns></returns>
        [HttpGet("{id}/gateway")]
        public IActionResult Gateway(Guid id)
        {
            var checkout = checkoutRepository.GetById(id);
            if (checkout == null)
            {
                return NotFound();
            }

            var viewModel = RequestPaymentViewModel.Create(
                checkout: checkout,
                iamportId: clientOptions.IamportId,
                paymentUrl: Url.Action(nameof(PaymentController.CreateAjax), "Payment"));
            return View(viewModel);
        }

        [HttpGet("{id}/PageNotFound")]
        public IActionResult PageNotFound(Guid id)
        {
            ViewData["Id"] = id;
            return View();
        }
    }
}

Samples/Sample.AspNetCore/Controllers/DirectPaymentController.cs
using Iamport.RestApi.Apis;
using Microsoft.AspNetCore.Mvc;
using Sample.AspNetCore.Repositories;
using Sample.AspNetCore.ViewModels;
using System;
using System.Threading.Tasks;
using Iamport.RestApi.Models;
using Iamport.RestApi;

namespace Sample.AspNetCore.Controllers
{
    [Route("[Controller]")]
    public class DirectPaymentController : Controller
    {
        private readonly IPaymentsApi paymentsApi;
        private readonly ISubscribeApi subscribeApi;
        private readonly CheckoutRepository checkoutRepository;
        private readonly PaymentRepository paymentRepository;
        private readonly string iamportId;
        public DirectPaymentController(
            IPaymentsApi paymentsApi,
            ISubscribeApi subscribeApi,
            CheckoutRepository checkoutRepository,
            PaymentRepository paymentRepository,
            IamportHttpClientOptions clientOptions)
        {
            this.paymentsApi = paymentsApi ?? throw new ArgumentNullException(nameof(paymentsApi));
            this.subscribeApi = subscribeApi ?? throw new ArgumentNullException(nameof(subscribeApi));
            this.checkoutRepository = checkoutRepository ?? throw new ArgumentNullException(nameof(checkoutRepository));
            this.paymentRepository = paymentRepository ?? throw new ArgumentNullException(nameof(paymentRepository));
            if (clientOptions == null)
            {
                throw new ArgumentNullException(nameof(clientOptions));
            }
            iamportId = clientOptions.IamportId;
        }

        /// <summary>
        /// 비인증 결제 페이지
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Index()
        {
            return View(new RequestDirectPaymentModel());
        }

        /// <summary>
        /// 비인증 결제 요청
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(RequestDirectPaymentModel input)
        {
            if (ModelState.IsValid == false)
            {
                return View(nameof(Index), input);
            }

            // 비인증 구매는 구매 요청을 즉시 처리 가능.
            var checkout = Models.Checkout.Create(
                name: input.Name,
                amount: input.Amount,
                paymentGateway: input.PaymentGateway,
                isDigital: false,
                useEscrow: false,
                paymentMethod: PaymentMethod.CreditCard,
                customerName: input.CustomerName,
                customerEmail: input.CustomerEmail,
                customerPhoneNumber: input.CustomerPhoneNumber,
                returnUrl: null,
                virtualBankExpirationTime: DateTimeOffset.UtcNow);
            checkoutRepository.Add(checkout);

            var payment = Models.Payment.Create(checkout.Id);

            var request = new DirectPaymentRequest
            {
                CustomerId = null,  // 등록된 사용자 빌링키 없이 한번 진행
                TransactionId = payment.TransactionId,
                Vat = input.Vat,
                Amount = input.Amount,
                Title = input.Name,
                CardNumber = input.CardNumber,
                AuthenticationNumber = input.AuthenticationNumber,
                Expiry = input.Expiry,
                PartialPassword = input.PartialPassword,
                InstallmentMonths = 0,
                BuyerName = input.CustomerName,
                Email = input.CustomerEmail,
                PhoneNumber = input.CustomerPhoneNumber,
                Address = input.CustomerAddress,
                PostCode = input.CustomerPostCode,
            };

            Payment iamportPayment = null;
            try
            {
                iamportPayment = await subscribeApi.DoDirectPaymentAsync(request);
            }
            catch (IamportResponseException ex)
            {
                ModelState.AddModelError("iamport", ex.Message);
                return View(nameof(Index), input);
            }
            
            paymentRepository.Add(payment);
            RefreshPayment(iamportPayment, payment);

            return RedirectToAction(nameof(Result), new { transactionId = payment.TransactionId });
        }

        /// <summary>
        /// 구매 결과 페이지
        /// </summary>
        /// <param name="transactionId">거래 고유 ID</param>
        /// <returns></returns>
        [HttpGet("{transactionId}")]
        public IActionResult Result(string transactionId)
        {
            var payment = paymentRepository.GetByTransactionId(transactionId);
            if (payment == null)
            {
                return PageNotFound(transactionId);
            }
            var checkout = checkoutRepository.GetById(payment.CheckoutId);
            if (checkout == null)
            {
                return PageNotFound(transactionId);
            }

            var viewModel = PaymentViewModel.Create(payment, checkout);
            return View(viewModel);
        }

        /// <summary>
        /// 지정한 거래 ID의 결제가 발견되지 않았습니다.
        /// </summary>
        /// <param name="transactionId">거래 ID</param>
        /// <returns></returns>
        [HttpGet("{transactionId}/pagenotfound")]
        public IActionResult PageNotFound(string transactionId)
        {
            ViewData["TransactionId"] = transactionId;
            return View(nameof(PageNotFound));
        }

        // TODO:
        // 이 로직은 비지니스 로직을 담고 있습니다.
        // 비즈니스 레이어로 옮기는 것이 좋습니다.

        private void RefreshPayment(Payment iamportPayment, Models.Payment payment)
        {
            // 기존 상태(payment.State)와 최신 상태(iamportPayment.Status)를 비교합니다.
            switch (iamportPayment.Status)
            {
                case PaymentStatus.Ready:
                    if (iamportPayment.Method == PaymentMethod.VirtualBank
                        && !string.IsNullOrEmpty(iamportPayment.VirtualBankAccount))
                    {
                        payment.SetAwatingForVirtualBank(
                            iamportPayment.IamportId,
                            iamportPayment.PaymentGatewayTransactionId,
                            iamportPayment.VirtualBankName,
                            iamportPayment.VirtualBankAccount,
                            iamportPayment.VirtualBankAccountHolder);
                    }
                    else
                    {
                        payment.SetInProgress(iamportPayment.IamportId);
                    }
                    break;
                case PaymentStatus.Paid:
                    switch (iamportPayment.Method)
                    {
                        case PaymentMethod.CreditCard:
                            payment.SetPaidForCreditCard(
                                iamportPayment.IamportId,
                                iamportPayment.PaidAtUtc,
                                iamportPayment.PaymentGatewayTransactionId,
                                iamportPayment.ApplyNumber,
                                iamportPayment.CreditCardCompanyName,
                                iamportPayment.InstallmentPlanPeriod);
                            break;
                        case PaymentMethod.VirtualBank:
                            payment.SetPaiedForVirtualBank(
                                iamportPayment.IamportId,
                                iamportPayment.PaidAtUtc,
                                iamportPayment.PaymentGatewayTransactionId,
                                iamportPayment.VirtualBankName,
                                iamportPayment.VirtualBankAccount,
                                iamportPayment.VirtualBankAccountHolder);
                            break;
                        case PaymentMethod.Transfer:
                        case PaymentMethod.Mobile:
                        case PaymentMethod.CultureLand:
                        case PaymentMethod.SmartCulture:
                        case PaymentMethod.HappyMoney:
                        default:
                            payment.SetPaidForOthers(
                                iamportPayment.IamportId,
                                iamportPayment.PaidAtUtc,
                                iamportPayment.PaymentGatewayTransactionId);
                            break;
                    }
                    break;
                case PaymentStatus.Cancelled:
                    payment.SetCancelled(
                        iamportPayment.IamportId,
                        iamportPayment.CancelledAtUtc,
                        iamportPayment.CancelledReason,
                        iamportPayment.CancelledAmount);
                    break;
                case PaymentStatus.Failed:
                    payment.SetFailed(
                        iamportPayment.IamportId,
                        iamportPayment.FailedAtUtc,
                        iamportPayment.FailedReason);
                    break;
                default:
                    break;
            }
            paymentRepository.Update(payment);
        }
    }
}

Samples/Sample.AspNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sample.AspNetCore</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Sample.AspNetCore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">아임포트 데모</a></li>
                    <li><a asp-area="" asp-controller="Checkout" asp-action="Index">구매-결제 시나리오</a></li>
                    <li><a asp-area="" asp-controller="DirectPayment" asp-action="Index">비인증 결제 시나리오</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Sample.AspNetCore</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"
                asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.validate">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"
                asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive">
        </script>
    </environment>
    <script type="text/javascript" src="~/js/site.min.js" asp-append-version="true"></script>

    @RenderSection("scripts", required: false)
</body>
</html>